### ISSUE TITLE
Azure OpenAI  is not support 

### ISSUE THREAD

**Issue by tonglei856** [antoineross/Autogen-UI#1]
I write the Azure OpenAI key in the file OAI_CONFIG_LIST, but it's error:

Error:  No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

**Comment by antoineross** [comment]
Edit the openai key to be azure. See here: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_research.ipynb

**Comment by tonglei856** [comment]
I edit the app.py code, write the config_list hard in code ,but it's alse error

```python
@cl.on_chat_start
async def on_chat_start():
  try:
    #config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
    config_list = [
    {
        "model": "gpt-4",
        "api_key": "<key>",
        "api_base": "https://xxx.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    },
    {
        "model": "gpt-3.5-turbo",
        "api_key": "<key>",
        "api_base": "https://xxx.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
    ]
```

2023-11-03 03:02:58 - Your app is available at http://localhost:8000
Task:  hi
GC messages:  0
Query_Agent (to chat_manager):

hi

--------------------------------------------------------------------------------
Error:  No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.


is not support "api_version": "2023-07-01-preview"?

**Comment by tonglei856** [comment]
I write my .env as follow:
```
OPENAI_API_TYPE="azure"
OPENAI_API_KEY="<azure openai key>"
OPENAI_API_BASE="https://<azure colleciton>.openai.azure.com/"
OPENAI_API_VERSION="2023-07-01-preview"
```
then it' work
